[package]
name = "c-lib"
version = "0.1.0"
edition = "2018"

[lib]
name = "qcs"
crate-type = ["dylib"]

[dependencies]
http = "0.2.4"
libc = "0.2.97"
qcs-api = { path = "../qcs-api" }
qcs-util = { path = "../qcs-util" }
thiserror = "1.0.25"
tokio = { version = "1.7.1", features = ["rt-multi-thread"] }
